### ISSUE TITLE
[Bug] Get campaign details not working

### ISSUE THREAD

**Issue by imilchev** [podkrepi-bg/module-campaigns#10]
**Describe the bug**
I tried to get a campaign via the gRPC interface but nothing happens. The code never returns. See the log from the module below:
```
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 5.0.5 initialized 'CampaignsContext' using provider 'Npgsql.EntityFrameworkCore.PostgreSQL' with options: SensitiveDataLoggingEnabled DetailedErrorsEnabled using snake-case naming  (culture=)
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (12ms) [Parameters=[@__Parse_0='31c37901-59ea-409a-81aa-1b41ae5f4a04'], CommandType='Text', CommandTimeout='30']
      SELECT c.id, c.beneficiary_id, c.campaign_subtype_id, c.campaign_type_id, c.created_at, c.currency, c.deadline, c.full_description, c.initiator_id, c.operator_id, c.optional_details, c.short_description, c.state, c.target_amount, c.title, c.updated_at, c0.id, c0.description, c0.name, c1.id, c1.campaign_type_id, c1.description, c1.name
      FROM campaign.campaigns AS c
      INNER JOIN campaign.campaign_types AS c0 ON c.campaign_type_id = c0.id
      LEFT JOIN campaign.campaign_subtypes AS c1 ON c.campaign_subtype_id = c1.id
      WHERE c.id = @__Parse_0
      LIMIT 1
info: Grpc.AspNetCore.Server.ServerCallHandler[7]
      Error status code 'Cancelled' raised.
      Grpc.Core.RpcException: Status(StatusCode="Cancelled", Detail="No message returned from method.")
         at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'gRPC - /podkrepibg.campaign.CampaignService/GetCampaignDetails'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 POST http://127.0.0.1:9001/podkrepibg.campaign.CampaignService/GetCampaignDetails application/grpc - - 200 0 application/grpc 24.9384ms
```

**To Reproduce**

1. Run the module
2. Create a campaign
3. Copy the returned ID
4. Call get campaign details for the ID that you copied
5. The call will never return and the logs of module will show the messages as shown above

P.S.: I used BloomRPC to test this.

**Expected behavior**
Get the campaign details

**Comment by preslavgerchev** [comment]
Fixed in https://github.com/podkrepi-bg/module-campaigns/commit/52a895ced6ef2e86dfe600fcbd5522998fd2fcf7
